CREATE TABLE perseus.coa (
    id integer NOT NULL,
    name public.citext NOT NULL,
    goo_type_id integer NOT NULL
);


ALTER TABLE perseus.coa OWNER TO perseus_owner;

ALTER TABLE perseus.coa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.coa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

