CREATE TABLE perseus.coa_spec (
    id integer NOT NULL,
    coa_id integer NOT NULL,
    property_id integer NOT NULL,
    upper_bound double precision,
    lower_bound double precision,
    equal_bound public.citext,
    upper_equal_bound double precision,
    lower_equal_bound double precision,
    result_precision integer DEFAULT 0
);


ALTER TABLE perseus.coa_spec OWNER TO perseus_owner;

ALTER TABLE perseus.coa_spec ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.coa_spec_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

