CREATE TABLE perseus.property (
    id integer NOT NULL,
    name public.citext NOT NULL,
    description public.citext,
    unit_id integer
);


ALTER TABLE perseus.property OWNER TO perseus_owner;

ALTER TABLE perseus.property ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.property_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

