CREATE TABLE perseus.property_option (
    id integer NOT NULL,
    property_id integer NOT NULL,
    value integer NOT NULL,
    label public.citext NOT NULL,
    disabled integer DEFAULT 0 NOT NULL
);


ALTER TABLE perseus.property_option OWNER TO perseus_owner;

ALTER TABLE perseus.property_option ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.property_option_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

