CREATE TABLE perseus.smurf (
    id integer NOT NULL,
    class_id integer NOT NULL,
    name public.citext NOT NULL,
    description public.citext,
    themis_method_id integer,
    disabled boolean DEFAULT false NOT NULL
);


ALTER TABLE perseus.smurf OWNER TO perseus_owner;

ALTER TABLE perseus.smurf ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.smurf_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

