CREATE TABLE perseus.smurf_property (
    id integer NOT NULL,
    property_id integer NOT NULL,
    sort_order integer DEFAULT 99 NOT NULL,
    smurf_id integer NOT NULL,
    disabled boolean DEFAULT false NOT NULL,
    calculated public.citext
);


ALTER TABLE perseus.smurf_property OWNER TO perseus_owner;

ALTER TABLE perseus.smurf_property ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.smurf_property_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

