CREATE TABLE perseus.unit (
    id integer NOT NULL,
    name public.citext NOT NULL,
    description public.citext,
    dimension_id integer,
    factor double precision,
    "offset" double precision
);


ALTER TABLE perseus.unit OWNER TO perseus_owner;

ALTER TABLE perseus.unit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.unit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

