CREATE TABLE perseus.field_map (
    id integer NOT NULL,
    field_map_block_id integer NOT NULL,
    name public.citext,
    description public.citext,
    display_order integer,
    setter public.citext,
    lookup public.citext,
    lookup_service public.citext,
    nullable integer,
    field_map_type_id integer NOT NULL,
    database_id public.citext,
    save_sequence integer NOT NULL,
    onchange public.citext,
    field_map_set_id integer NOT NULL
);


ALTER TABLE perseus.field_map OWNER TO perseus_owner;

ALTER TABLE perseus.field_map ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.field_map_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

