CREATE TABLE perseus.field_map_block (
    id integer NOT NULL,
    filter public.citext,
    scope public.citext
);


ALTER TABLE perseus.field_map_block OWNER TO perseus_owner;

ALTER TABLE perseus.field_map_block ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.field_map_block_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

