CREATE TABLE perseus.cm_application_group (
    application_group_id integer NOT NULL,
    label public.citext NOT NULL
);


ALTER TABLE perseus.cm_application_group OWNER TO perseus_owner;

ALTER TABLE perseus.cm_application_group ALTER COLUMN application_group_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.cm_application_group_application_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

