CREATE TABLE perseus.field_map_display_type (
    id integer NOT NULL,
    field_map_id integer NOT NULL,
    display_type_id integer NOT NULL,
    display public.citext NOT NULL,
    display_layout_id integer DEFAULT 1 NOT NULL,
    manditory integer DEFAULT 0 NOT NULL
);


ALTER TABLE perseus.field_map_display_type OWNER TO perseus_owner;

ALTER TABLE perseus.field_map_display_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.field_map_display_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

