CREATE TABLE perseus.container (
    id integer NOT NULL,
    container_type_id integer NOT NULL,
    name public.citext,
    uid public.citext NOT NULL,
    mass double precision,
    left_id integer DEFAULT 1 NOT NULL,
    right_id integer DEFAULT 2 NOT NULL,
    scope_id public.citext DEFAULT (gen_random_uuid())::character varying(50) NOT NULL,
    position_name public.citext,
    position_x_coordinate public.citext,
    position_y_coordinate public.citext,
    depth integer DEFAULT 0 NOT NULL,
    created_on timestamp without time zone DEFAULT LOCALTIMESTAMP
);


ALTER TABLE perseus.container OWNER TO perseus_owner;

ALTER TABLE perseus.container ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.container_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

