CREATE TABLE perseus.container_history (
    id integer NOT NULL,
    history_id integer NOT NULL,
    container_id integer NOT NULL
);


ALTER TABLE perseus.container_history OWNER TO perseus_owner;

ALTER TABLE perseus.container_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.container_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

