CREATE TABLE perseus.container_type (
    id integer NOT NULL,
    name public.citext NOT NULL,
    is_parent boolean DEFAULT false NOT NULL,
    is_equipment boolean DEFAULT false NOT NULL,
    is_single boolean DEFAULT false NOT NULL,
    is_restricted boolean DEFAULT false NOT NULL,
    is_gooable boolean DEFAULT false NOT NULL
);


ALTER TABLE perseus.container_type OWNER TO perseus_owner;

ALTER TABLE perseus.container_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.container_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

