CREATE TABLE perseus.container_type_position (
    id integer NOT NULL,
    parent_container_type_id integer NOT NULL,
    child_container_type_id integer,
    position_name public.citext,
    position_x_coordinate public.citext,
    position_y_coordinate public.citext
);


ALTER TABLE perseus.container_type_position OWNER TO perseus_owner;

ALTER TABLE perseus.container_type_position ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.container_type_position_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

