CREATE TABLE perseus.external_goo_type (
    id integer NOT NULL,
    goo_type_id integer NOT NULL,
    external_label public.citext NOT NULL,
    manufacturer_id integer NOT NULL
);


ALTER TABLE perseus.external_goo_type OWNER TO perseus_owner;

ALTER TABLE perseus.external_goo_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.external_goo_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

