CREATE TABLE perseus.cm_group (
    group_id integer NOT NULL,
    name public.citext NOT NULL,
    domain_id public.citext NOT NULL,
    is_active boolean NOT NULL,
    last_modified timestamp without time zone NOT NULL
);


ALTER TABLE perseus.cm_group OWNER TO perseus_owner;

ALTER TABLE perseus.cm_group ALTER COLUMN group_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.cm_group_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

