CREATE TABLE perseus.fatsmurf (
    id integer NOT NULL,
    smurf_id integer NOT NULL,
    recycled_bottoms_id integer,
    name public.citext,
    description public.citext,
    added_on timestamp without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
    run_on timestamp without time zone,
    duration double precision,
    added_by integer NOT NULL,
    themis_sample_id integer,
    uid public.citext NOT NULL,
    run_complete timestamp without time zone,
    container_id integer,
    organization_id integer DEFAULT 1,
    workflow_step_id integer,
    updated_on timestamp without time zone DEFAULT LOCALTIMESTAMP,
    inserted_on timestamp without time zone DEFAULT LOCALTIMESTAMP,
    triton_task_id integer
);


ALTER TABLE perseus.fatsmurf OWNER TO perseus_owner;

ALTER TABLE perseus.fatsmurf ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.fatsmurf_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

