CREATE TABLE perseus.fatsmurf_attachment (
    id integer NOT NULL,
    fatsmurf_id integer NOT NULL,
    added_on timestamp without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
    added_by integer NOT NULL,
    description public.citext NOT NULL,
    attachment_name public.citext,
    attachment_mime_type public.citext,
    attachment bytea
);


ALTER TABLE perseus.fatsmurf_attachment OWNER TO perseus_owner;

ALTER TABLE perseus.fatsmurf_attachment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.fatsmurf_attachment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

