CREATE TABLE perseus.fatsmurf_comment (
    id integer NOT NULL,
    fatsmurf_id integer NOT NULL,
    added_on timestamp without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
    added_by integer NOT NULL,
    comment public.citext NOT NULL
);


ALTER TABLE perseus.fatsmurf_comment OWNER TO perseus_owner;

ALTER TABLE perseus.fatsmurf_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.fatsmurf_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

