CREATE TABLE perseus.fatsmurf_reading (
    id integer NOT NULL,
    name public.citext NOT NULL,
    fatsmurf_id integer NOT NULL,
    added_on timestamp without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
    added_by integer DEFAULT 1 NOT NULL
);


ALTER TABLE perseus.fatsmurf_reading OWNER TO perseus_owner;

ALTER TABLE perseus.fatsmurf_reading ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.fatsmurf_reading_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

