CREATE TABLE perseus.feed_type (
    id integer NOT NULL,
    added_by integer NOT NULL,
    updated_by_id integer,
    name public.citext,
    description public.citext,
    correction_method public.citext DEFAULT 'SIMPLE'::character varying NOT NULL,
    correction_factor double precision DEFAULT 1.0 NOT NULL,
    disabled boolean DEFAULT (0)::boolean NOT NULL,
    added_on timestamp without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
    updated_on timestamp without time zone DEFAULT LOCALTIMESTAMP
);


ALTER TABLE perseus.feed_type OWNER TO perseus_owner;

ALTER TABLE perseus.feed_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.feed_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

