CREATE TABLE perseus.field_map_display_type_user (
    id integer NOT NULL,
    field_map_display_type_id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE perseus.field_map_display_type_user OWNER TO perseus_owner;

ALTER TABLE perseus.field_map_display_type_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.field_map_display_type_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

