CREATE TABLE perseus.goo (
    id integer NOT NULL,
    name public.citext,
    description public.citext,
    added_on timestamp without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
    added_by integer NOT NULL,
    original_volume double precision DEFAULT 0,
    original_mass double precision DEFAULT 0,
    goo_type_id integer DEFAULT 8 NOT NULL,
    manufacturer_id integer DEFAULT 1 NOT NULL,
    received_on date,
    uid public.citext NOT NULL,
    project_id smallint,
    container_id integer,
    workflow_step_id integer,
    updated_on timestamp without time zone DEFAULT LOCALTIMESTAMP,
    inserted_on timestamp without time zone DEFAULT LOCALTIMESTAMP,
    triton_task_id integer,
    recipe_id integer,
    recipe_part_id integer,
    catalog_label public.citext
);


ALTER TABLE perseus.goo OWNER TO perseus_owner;

ALTER TABLE perseus.goo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.goo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

