CREATE TABLE perseus.goo_attachment (
    id integer NOT NULL,
    goo_id integer NOT NULL,
    added_on timestamp without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
    added_by integer NOT NULL,
    description public.citext,
    attachment_name public.citext NOT NULL,
    attachment_mime_type public.citext,
    attachment bytea,
    goo_attachment_type_id integer
);


ALTER TABLE perseus.goo_attachment OWNER TO perseus_owner;

ALTER TABLE perseus.goo_attachment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.goo_attachment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

