CREATE TABLE perseus.goo_comment (
    id integer NOT NULL,
    goo_id integer NOT NULL,
    added_on timestamp without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
    added_by integer NOT NULL,
    comment public.citext NOT NULL,
    category public.citext
);


ALTER TABLE perseus.goo_comment OWNER TO perseus_owner;

ALTER TABLE perseus.goo_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.goo_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

