CREATE TABLE perseus.goo_history (
    id integer NOT NULL,
    history_id integer NOT NULL,
    goo_id integer NOT NULL
);


ALTER TABLE perseus.goo_history OWNER TO perseus_owner;

ALTER TABLE perseus.goo_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.goo_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

