CREATE TABLE perseus.goo_process_queue_type (
    id integer NOT NULL,
    name public.citext NOT NULL
);


ALTER TABLE perseus.goo_process_queue_type OWNER TO perseus_owner;

ALTER TABLE perseus.goo_process_queue_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.goo_process_queue_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

