CREATE TABLE perseus.goo_type (
    id integer NOT NULL,
    name public.citext NOT NULL,
    color public.citext,
    left_id integer NOT NULL,
    right_id integer NOT NULL,
    scope_id public.citext NOT NULL,
    disabled integer DEFAULT 0 NOT NULL,
    casrn public.citext,
    iupac public.citext,
    depth integer DEFAULT 0 NOT NULL,
    abbreviation public.citext,
    density_kg_l double precision
);


ALTER TABLE perseus.goo_type OWNER TO perseus_owner;

ALTER TABLE perseus.goo_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.goo_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

