CREATE TABLE perseus.goo_type_combine_component (
    id integer NOT NULL,
    goo_type_combine_target_id integer NOT NULL,
    goo_type_id integer NOT NULL
);


ALTER TABLE perseus.goo_type_combine_component OWNER TO perseus_owner;

ALTER TABLE perseus.goo_type_combine_component ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.goo_type_combine_component_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

