CREATE TABLE perseus.goo_type_combine_target (
    id integer NOT NULL,
    goo_type_id integer NOT NULL,
    sort_order integer NOT NULL
);


ALTER TABLE perseus.goo_type_combine_target OWNER TO perseus_owner;

ALTER TABLE perseus.goo_type_combine_target ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.goo_type_combine_target_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

