CREATE TABLE perseus.history (
    id integer NOT NULL,
    history_type_id integer NOT NULL,
    creator_id integer NOT NULL,
    created_on timestamp without time zone DEFAULT LOCALTIMESTAMP NOT NULL
);


ALTER TABLE perseus.history OWNER TO perseus_owner;

ALTER TABLE perseus.history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

