CREATE TABLE perseus.history_value (
    id integer NOT NULL,
    history_id integer NOT NULL,
    value public.citext
);


ALTER TABLE perseus.history_value OWNER TO perseus_owner;

ALTER TABLE perseus.history_value ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.history_value_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

