CREATE TABLE perseus.m_number (
    id integer NOT NULL,
    md5_hash text NOT NULL
);


ALTER TABLE perseus.m_number OWNER TO perseus_owner;

ALTER TABLE perseus.m_number ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.m_number_id_seq
    START WITH 900000
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

