CREATE TABLE perseus.manufacturer (
    id integer NOT NULL,
    name public.citext NOT NULL,
    location public.citext,
    goo_prefix public.citext
);


ALTER TABLE perseus.manufacturer OWNER TO perseus_owner;

ALTER TABLE perseus.manufacturer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.manufacturer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

