CREATE TABLE perseus.material_inventory (
    id integer NOT NULL,
    material_id integer NOT NULL,
    location_container_id integer NOT NULL,
    is_active boolean NOT NULL,
    current_volume_l real,
    current_mass_kg real,
    created_by_id integer NOT NULL,
    created_on timestamp without time zone,
    updated_by_id integer,
    updated_on timestamp without time zone,
    allocation_container_id integer,
    recipe_id integer,
    comment public.citext,
    expiration_date date,
    inventory_type_id integer NOT NULL
);


ALTER TABLE perseus.material_inventory OWNER TO perseus_owner;

ALTER TABLE perseus.material_inventory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.material_inventory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

