CREATE TABLE perseus.material_inventory_threshold (
    id integer NOT NULL,
    material_type_id integer NOT NULL,
    min_item_count integer,
    max_item_count integer,
    min_volume_l double precision,
    max_volume_l double precision,
    min_mass_kg double precision,
    max_mass_kg double precision,
    created_by_id integer NOT NULL,
    created_on timestamp without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
    updated_by_id integer,
    updated_on timestamp without time zone,
    inventory_type_id integer NOT NULL
);


ALTER TABLE perseus.material_inventory_threshold OWNER TO perseus_owner;

ALTER TABLE perseus.material_inventory_threshold ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.material_inventory_threshold_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

