CREATE TABLE perseus.material_inventory_type (
    id integer NOT NULL,
    name public.citext NOT NULL,
    description public.citext,
    is_active boolean DEFAULT true NOT NULL
);


ALTER TABLE perseus.material_inventory_type OWNER TO perseus_owner;

ALTER TABLE perseus.material_inventory_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.material_inventory_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

