CREATE TABLE perseus.material_qc (
    id integer NOT NULL,
    material_id integer NOT NULL,
    entity_type_name public.citext NOT NULL,
    foreign_entity_id integer NOT NULL,
    qc_process_uid public.citext NOT NULL
);


ALTER TABLE perseus.material_qc OWNER TO perseus_owner;

ALTER TABLE perseus.material_qc ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.material_qc_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

