CREATE TABLE perseus.perseus_user (
    id integer NOT NULL,
    name public.citext NOT NULL,
    domain_id public.citext,
    login public.citext,
    mail public.citext,
    admin boolean DEFAULT false NOT NULL,
    super boolean DEFAULT false NOT NULL,
    common_id integer,
    manufacturer_id integer DEFAULT 1 NOT NULL
);


ALTER TABLE perseus.perseus_user OWNER TO perseus_owner;

ALTER TABLE perseus.perseus_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.perseus_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

