CREATE TABLE perseus.poll (
    id integer NOT NULL,
    smurf_property_id integer NOT NULL,
    fatsmurf_reading_id integer NOT NULL,
    value public.citext,
    standard_deviation double precision,
    detection integer,
    limit_of_detection double precision,
    limit_of_quantification double precision,
    lower_calibration_limit double precision,
    upper_calibration_limit double precision,
    bounds_limit integer
);


ALTER TABLE perseus.poll OWNER TO perseus_owner;

ALTER TABLE perseus.poll ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.poll_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

