CREATE TABLE perseus.recipe (
    id integer NOT NULL,
    name public.citext NOT NULL,
    goo_type_id integer NOT NULL,
    description public.citext,
    sop public.citext,
    workflow_id integer,
    added_by integer NOT NULL,
    added_on timestamp without time zone NOT NULL,
    is_preferred boolean DEFAULT (0)::boolean NOT NULL,
    qc boolean DEFAULT (0)::boolean NOT NULL,
    is_archived boolean DEFAULT (0)::boolean NOT NULL,
    feed_type_id integer,
    stock_concentration double precision,
    sterilization_method public.citext,
    inoculant_percent double precision,
    post_inoc_volume_ml double precision
);


ALTER TABLE perseus.recipe OWNER TO perseus_owner;

ALTER TABLE perseus.recipe ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.recipe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

