CREATE TABLE perseus.recipe_part (
    id integer NOT NULL,
    recipe_id integer NOT NULL,
    description public.citext,
    goo_type_id integer NOT NULL,
    amount double precision NOT NULL,
    unit_id integer NOT NULL,
    workflow_step_id integer,
    "position" integer,
    part_recipe_id integer,
    target_conc_in_media double precision,
    target_post_inoc_conc double precision
);


ALTER TABLE perseus.recipe_part OWNER TO perseus_owner;

ALTER TABLE perseus.recipe_part ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.recipe_part_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

