CREATE TABLE perseus.robot_log (
    id integer NOT NULL,
    class_id integer NOT NULL,
    source public.citext,
    created_on timestamp without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
    log_text public.citext NOT NULL,
    file_name public.citext,
    robot_log_checksum public.citext,
    started_on timestamp without time zone,
    completed_on timestamp without time zone,
    loaded_on timestamp without time zone,
    loaded integer DEFAULT 0 NOT NULL,
    loadable integer DEFAULT 0 NOT NULL,
    robot_run_id integer,
    robot_log_type_id integer NOT NULL
);


ALTER TABLE perseus.robot_log OWNER TO perseus_owner;

ALTER TABLE perseus.robot_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.robot_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

