CREATE TABLE perseus.robot_log_container_sequence (
    id integer NOT NULL,
    robot_log_id integer NOT NULL,
    container_id integer NOT NULL,
    sequence_type_id integer NOT NULL,
    processed_on timestamp without time zone
);


ALTER TABLE perseus.robot_log_container_sequence OWNER TO perseus_owner;

ALTER TABLE perseus.robot_log_container_sequence ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.robot_log_container_sequence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

