CREATE TABLE perseus.robot_log_error (
    id integer NOT NULL,
    robot_log_id integer NOT NULL,
    error_text public.citext NOT NULL
);


ALTER TABLE perseus.robot_log_error OWNER TO perseus_owner;

ALTER TABLE perseus.robot_log_error ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.robot_log_error_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

