CREATE TABLE perseus.robot_log_read (
    id integer NOT NULL,
    robot_log_id integer NOT NULL,
    source_barcode public.citext NOT NULL,
    property_id integer NOT NULL,
    value public.citext,
    source_position public.citext,
    source_material_id integer
);


ALTER TABLE perseus.robot_log_read OWNER TO perseus_owner;

ALTER TABLE perseus.robot_log_read ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.robot_log_read_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

