CREATE TABLE perseus.robot_log_transfer (
    id integer NOT NULL,
    robot_log_id integer NOT NULL,
    source_barcode public.citext NOT NULL,
    destination_barcode public.citext NOT NULL,
    transfer_time timestamp without time zone,
    transfer_volume public.citext,
    source_position public.citext,
    destination_position public.citext,
    material_type_id integer,
    source_material_id integer,
    destination_material_id integer
);


ALTER TABLE perseus.robot_log_transfer OWNER TO perseus_owner;

ALTER TABLE perseus.robot_log_transfer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.robot_log_transfer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

