CREATE TABLE perseus.robot_log_type (
    id integer NOT NULL,
    name public.citext NOT NULL,
    auto_process integer NOT NULL,
    destination_container_type_id integer
);


ALTER TABLE perseus.robot_log_type OWNER TO perseus_owner;

ALTER TABLE perseus.robot_log_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.robot_log_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

