CREATE TABLE perseus.robot_run (
    id integer NOT NULL,
    robot_id integer,
    name public.citext NOT NULL,
    all_qc_passed boolean,
    all_themis_submitted boolean
);


ALTER TABLE perseus.robot_run OWNER TO perseus_owner;

ALTER TABLE perseus.robot_run ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.robot_run_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

