CREATE TABLE perseus.s_number (
    id integer NOT NULL,
    md5_hash text NOT NULL
);


ALTER TABLE perseus.s_number OWNER TO perseus_owner;

ALTER TABLE perseus.s_number ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.s_number_id_seq
    START WITH 1100000
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

