CREATE TABLE perseus.saved_search (
    id integer NOT NULL,
    class_id integer,
    name public.citext NOT NULL,
    added_on timestamp without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
    added_by integer NOT NULL,
    is_private integer DEFAULT 1 NOT NULL,
    include_downstream integer DEFAULT 0 NOT NULL,
    parameter_string public.citext NOT NULL
);


ALTER TABLE perseus.saved_search OWNER TO perseus_owner;

ALTER TABLE perseus.saved_search ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.saved_search_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

