CREATE TABLE perseus.cm_user (
    user_id integer NOT NULL,
    domain_id public.citext,
    is_active boolean NOT NULL,
    name public.citext NOT NULL,
    login public.citext,
    email public.citext,
    object_id uuid
);


ALTER TABLE perseus.cm_user OWNER TO perseus_owner;

ALTER TABLE perseus.cm_user ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.cm_user_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

