CREATE TABLE perseus.scraper (
    id integer NOT NULL,
    "timestamp" timestamp without time zone,
    message public.citext,
    filetype public.citext,
    filename public.citext,
    filenamesavedas public.citext,
    receivedfrom public.citext,
    file bytea,
    result public.citext,
    complete boolean,
    scraperid public.citext,
    scrapingstartedon timestamp without time zone,
    scrapingfinishedon timestamp without time zone,
    scrapingstatus public.citext,
    scrapersendto public.citext,
    scrapermessage public.citext,
    active public.citext,
    controlfileid integer,
    documentid public.citext
);


ALTER TABLE perseus.scraper OWNER TO perseus_owner;

ALTER TABLE perseus.scraper ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.scraper_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

