CREATE TABLE perseus.sequence_type (
    id integer NOT NULL,
    name public.citext NOT NULL
);


ALTER TABLE perseus.sequence_type OWNER TO perseus_owner;

ALTER TABLE perseus.sequence_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.sequence_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

