CREATE TABLE perseus.smurf_goo_type (
    id integer NOT NULL,
    smurf_id integer NOT NULL,
    goo_type_id integer,
    is_input boolean DEFAULT false NOT NULL
);


ALTER TABLE perseus.smurf_goo_type OWNER TO perseus_owner;

ALTER TABLE perseus.smurf_goo_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.smurf_goo_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

