CREATE TABLE perseus.smurf_group (
    id integer NOT NULL,
    name public.citext NOT NULL,
    added_by integer NOT NULL,
    is_public boolean DEFAULT false NOT NULL
);


ALTER TABLE perseus.smurf_group OWNER TO perseus_owner;

ALTER TABLE perseus.smurf_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.smurf_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

