CREATE TABLE perseus.smurf_group_member (
    id integer NOT NULL,
    smurf_group_id integer NOT NULL,
    smurf_id integer NOT NULL
);


ALTER TABLE perseus.smurf_group_member OWNER TO perseus_owner;

ALTER TABLE perseus.smurf_group_member ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.smurf_group_member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

