CREATE TABLE perseus.submission (
    id integer NOT NULL,
    submitter_id integer NOT NULL,
    added_on timestamp without time zone NOT NULL,
    label public.citext
);


ALTER TABLE perseus.submission OWNER TO perseus_owner;

ALTER TABLE perseus.submission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.submission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

