CREATE TABLE perseus.submission_entry (
    id integer NOT NULL,
    assay_type_id integer NOT NULL,
    material_id integer NOT NULL,
    status character varying(19) NOT NULL,
    priority character varying(6) NOT NULL,
    submission_id integer NOT NULL,
    prepped_by_id integer,
    themis_tray_id integer,
    sample_type character varying(7) NOT NULL,
    CONSTRAINT ck__submissio__prior__7b3ee7aa CHECK ((((priority)::text = 'normal'::text) OR ((priority)::text = 'urgent'::text))),
    CONSTRAINT ck__submissio__sampl__4814495f CHECK ((((sample_type)::text = 'overlay'::text) OR ((sample_type)::text = 'broth'::text) OR ((sample_type)::text = 'pellet'::text) OR ((sample_type)::text = 'none'::text))),
    CONSTRAINT ck__submissio__statu__7a4ac371 CHECK ((((status)::text = 'prepped'::text) OR ((status)::text = 'submitted_to_themis'::text) OR ((status)::text = 'prepping'::text) OR ((status)::text = 'error'::text) OR ((status)::text = 'to_be_prepped'::text) OR ((status)::text = 'rejected'::text)))
);


ALTER TABLE perseus.submission_entry OWNER TO perseus_owner;

ALTER TABLE perseus.submission_entry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.submission_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

