CREATE TABLE perseus.workflow (
    id integer NOT NULL,
    name public.citext NOT NULL,
    added_on timestamp without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
    added_by integer DEFAULT 23 NOT NULL,
    disabled integer DEFAULT 0 NOT NULL,
    manufacturer_id integer NOT NULL,
    description public.citext,
    category public.citext
);


ALTER TABLE perseus.workflow OWNER TO perseus_owner;

ALTER TABLE perseus.workflow ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.workflow_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

