CREATE TABLE perseus.workflow_attachment (
    id integer NOT NULL,
    workflow_id integer NOT NULL,
    added_on timestamp without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
    added_by integer NOT NULL,
    attachment_name public.citext,
    attachment_mime_type public.citext,
    attachment bytea
);


ALTER TABLE perseus.workflow_attachment OWNER TO perseus_owner;

ALTER TABLE perseus.workflow_attachment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.workflow_attachment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

