CREATE TABLE perseus.workflow_section (
    id integer NOT NULL,
    workflow_id integer NOT NULL,
    name public.citext NOT NULL,
    starting_step_id integer NOT NULL
);


ALTER TABLE perseus.workflow_section OWNER TO perseus_owner;

ALTER TABLE perseus.workflow_section ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.workflow_section_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

