CREATE TABLE perseus.workflow_step (
    id integer NOT NULL,
    left_id integer,
    right_id integer,
    scope_id integer NOT NULL,
    class_id integer NOT NULL,
    name public.citext NOT NULL,
    smurf_id integer,
    goo_type_id integer,
    property_id integer,
    label public.citext,
    optional boolean DEFAULT false NOT NULL,
    goo_amount_unit_id integer DEFAULT 61,
    depth integer,
    description public.citext,
    recipe_factor double precision,
    parent_id integer,
    child_order integer
);


ALTER TABLE perseus.workflow_step OWNER TO perseus_owner;

ALTER TABLE perseus.workflow_step ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perseus.workflow_step_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

