-- =============================================================================
-- pgTAP Test: trigger <TRIGGER_NAME> on <SCHEMA>.<TABLE>
-- Type: TRIGGER
-- Generated by: pgtap-tdd-testing skill
-- Requirement: <BRIEF_DESCRIPTION>
-- =============================================================================
BEGIN;
SELECT plan(<N>);

-- =============================================================================
-- SECTION 1: Structure / Existence
-- =============================================================================

-- Trigger exists
SELECT has_trigger(
    '<SCHEMA>', '<TABLE>', '<TRIGGER>',
    '<trigger> should exist on <table>'
);

-- Trigger calls the expected function
SELECT trigger_is(
    '<SCHEMA>', '<TABLE>', '<TRIGGER>',
    '<FUNCTION_SCHEMA>', '<TRIGGER_FUNCTION>',
    '<trigger> should call <trigger_function>'
);

-- =============================================================================
-- SECTION 2: Setup test data
-- =============================================================================

-- Initial seed row that we will modify to fire the trigger
INSERT INTO <SCHEMA>.<TABLE> (<col1>, <col2>) VALUES (<val1>, <val2>);

-- =============================================================================
-- SECTION 3: Trigger fires on EXPECTED events
-- =============================================================================

-- Example: UPDATE fires the trigger
UPDATE <SCHEMA>.<TABLE> SET <col2> = <new_val> WHERE <col1> = <val1>;

-- Verify the side effect (e.g., audit row)
SELECT is(
    (SELECT count(*)::integer FROM <audit_table>
     WHERE <table_ref> = '<TABLE>' AND <key_ref> = <val1>),
    1,
    'UPDATE should create exactly one audit entry'
);

-- Verify the captured payload
SELECT is(
    (SELECT old_value FROM <audit_table>
     WHERE <table_ref> = '<TABLE>' AND <key_ref> = <val1>),
    <val2>::text,
    'audit should capture the old value'
);

-- =============================================================================
-- SECTION 4: Trigger does NOT fire on EXCLUDED events
-- =============================================================================

-- Example: if the trigger is UPDATE-only, INSERT should not fire it
INSERT INTO <SCHEMA>.<TABLE> (<col1>, <col2>) VALUES (<val3>, <val4>);

SELECT is(
    (SELECT count(*)::integer FROM <audit_table>
     WHERE <table_ref> = '<TABLE>' AND <key_ref> = <val3>),
    0,
    'INSERT should not create audit entry for UPDATE-only trigger'
);

-- =============================================================================
-- SECTION 5: Edge cases
-- =============================================================================

-- DELETE behavior (if trigger handles deletes)
DELETE FROM <SCHEMA>.<TABLE> WHERE <col1> = <val1>;

SELECT is(
    (SELECT count(*)::integer FROM <audit_table>
     WHERE <table_ref> = '<TABLE>' AND <key_ref> = <val1>
       AND operation = 'DELETE'),
    1,
    'DELETE should create audit entry with operation = DELETE'
);

-- =============================================================================
-- SECTION 6: Cleanup
-- =============================================================================

SELECT * FROM finish();
ROLLBACK;
