-- =============================================================================
-- pgTAP Test: <SCHEMA>.<FUNCTION_NAME>(<ARG_TYPES>)
-- Type: FUNCTION
-- Generated by: pgtap-tdd-testing skill
-- Requirement: <BRIEF_DESCRIPTION>
-- =============================================================================
BEGIN;
SELECT plan(<N>);

-- =============================================================================
-- SECTION 1: Structure / Existence
-- =============================================================================

-- Function exists with the expected signature
SELECT has_function(
    '<SCHEMA>', '<FUNCTION>', ARRAY['<arg1_type>', '<arg2_type>'],
    '<function>(<args>) should exist'
);

-- Returns the expected type (use 'setof <type>' for set-returning functions)
SELECT function_returns(
    '<SCHEMA>', '<FUNCTION>', ARRAY['<arg1_type>', '<arg2_type>'],
    '<return_type>',
    '<function> should return <return_type>'
);

-- Implementation language
SELECT function_lang_is(
    '<SCHEMA>', '<FUNCTION>', ARRAY['<arg1_type>', '<arg2_type>'],
    'plpgsql',
    '<function> should be written in plpgsql'
);

-- Distinguish normal function from aggregate, window, or procedure
SELECT is_normal_function(
    '<SCHEMA>', '<FUNCTION>', ARRAY['<arg1_type>', '<arg2_type>'],
    '<function> should be a normal function'
);

-- Optional: volatility
-- SELECT volatility_is('<SCHEMA>', '<FUNCTION>',
--     ARRAY['<arg1_type>', '<arg2_type>'], 'stable',
--     '<function> should be STABLE');

-- =============================================================================
-- SECTION 2: Setup test data
-- =============================================================================

-- INSERTs needed to exercise the function. All rolled back by the outer ROLLBACK.
-- INSERT INTO <table> (col1, col2) VALUES
--     (<val1>, <val2>),
--     (<val3>, <val4>);

-- =============================================================================
-- SECTION 3: Happy path behavior
-- =============================================================================

-- Always cast both sides explicitly to avoid type-mismatch failures
SELECT is(
    <SCHEMA>.<FUNCTION>(<input>),
    <expected_value>::<type>,
    '<happy path description>'
);

-- =============================================================================
-- SECTION 4: Edge cases
-- =============================================================================

-- NULL handling — required for every function
SELECT is(
    <SCHEMA>.<FUNCTION>(NULL),
    NULL::<return_type>,
    'NULL parameter should return NULL'
);

-- Empty / boundary cases
-- SELECT is(<SCHEMA>.<FUNCTION>(0), <result>::<type>, 'zero input');
-- SELECT is(<SCHEMA>.<FUNCTION>(-1), <result>::<type>, 'negative input');
-- SELECT is(<SCHEMA>.<FUNCTION>(2147483647), <result>::<type>, 'max int');

-- =============================================================================
-- SECTION 5: Error cases
-- =============================================================================

-- At least one error case is required. Pass NULL for errmsg to skip locale-
-- sensitive message checks; rely on the SQLSTATE error code.
SELECT throws_ok(
    $$SELECT <SCHEMA>.<FUNCTION>(<bad_input>)$$,
    'P0001',                              -- common code for RAISE EXCEPTION
    NULL,                                 -- skip message check (locale-safe)
    '<bad input> should raise <error code>'
);

-- =============================================================================
-- SECTION 6: Cleanup
-- =============================================================================

SELECT * FROM finish();
ROLLBACK;
