-- =============================================================================
-- pgTAP Test: <SCHEMA>.<TABLE_NAME>
-- Type: TABLE
-- Generated by: pgtap-tdd-testing skill
-- Requirement: <BRIEF_DESCRIPTION>
-- =============================================================================
BEGIN;
SELECT plan(<N>);

-- =============================================================================
-- SECTION 1: Structure / Existence
-- =============================================================================

-- Table exists
SELECT has_table(
    '<SCHEMA>', '<TABLE>',
    '<table> table should exist'
);

-- Exact column set (catches schema drift — fails on extra OR missing columns)
SELECT columns_are(
    '<SCHEMA>', '<TABLE>',
    ARRAY['<col1>', '<col2>', '<col3>'],
    '<table> should have exactly these columns'
);

-- Column types (use canonical PG names: 'integer', 'character varying(255)',
-- 'timestamp with time zone', 'numeric(10,2)', etc.)
SELECT col_type_is('<SCHEMA>', '<TABLE>', '<col1>', 'integer',
    '<col1> should be integer');
SELECT col_type_is('<SCHEMA>', '<TABLE>', '<col2>', 'character varying(255)',
    '<col2> should be varchar(255)');

-- Primary key
SELECT has_pk('<SCHEMA>', '<TABLE>', '<table> should have a primary key');
SELECT col_is_pk('<SCHEMA>', '<TABLE>', '<col1>',
    '<col1> should be the primary key');

-- NOT NULL constraints (one assertion per required column)
SELECT col_not_null('<SCHEMA>', '<TABLE>', '<col2>',
    '<col2> should be NOT NULL');

-- UNIQUE constraints (one per unique column)
-- SELECT col_is_unique('<SCHEMA>', '<TABLE>', '<col2>',
--     '<col2> should be UNIQUE');

-- Foreign keys (use fk_ok for full PK→FK relationship validation)
-- SELECT fk_ok(
--     '<SCHEMA>', '<TABLE>',  '<fk_col>',
--     '<PARENT_SCHEMA>', '<PARENT_TABLE>', '<PARENT_PK>',
--     '<fk_col> should reference <parent_table>(<parent_pk>)'
-- );

-- Default values
-- SELECT col_default_is('<SCHEMA>', '<TABLE>', '<col>', '<default_expr>',
--     '<col> should default to <expr>');

-- =============================================================================
-- SECTION 6: Cleanup
-- =============================================================================

SELECT * FROM finish();
ROLLBACK;
