-- =============================================================================
-- pgTAP Test: RLS policies on <SCHEMA>.<TABLE>
-- Type: RLS
-- Generated by: pgtap-tdd-testing skill
-- Requirement: <BRIEF_DESCRIPTION>
--
-- Key insights:
--   1. Blocked SELECT returns EMPTY results, not an error → use is_empty/isnt_empty
--   2. Blocked INSERT/UPDATE/DELETE throws 42501 (insufficient_privilege)
--   3. Superusers bypass RLS — verify behavior as the restricted role only
-- =============================================================================
BEGIN;
SELECT plan(<N>);

-- =============================================================================
-- SECTION 1: Structure / Existence
-- =============================================================================

-- Exact policy set (catches new policies added without a corresponding test)
SELECT policies_are(
    '<SCHEMA>', '<TABLE>',
    ARRAY['<policy1>', '<policy2>'],
    '<table> should have exactly these policies'
);

-- Each policy applies to the right command
SELECT policy_cmd_is(
    '<SCHEMA>', '<TABLE>', '<policy_select>'::name,
    'select',
    '<policy_select> should apply to SELECT'
);

SELECT policy_cmd_is(
    '<SCHEMA>', '<TABLE>', '<policy_insert>'::name,
    'insert',
    '<policy_insert> should apply to INSERT'
);

-- =============================================================================
-- SECTION 2: Setup as superuser (RLS bypassed during seed)
-- =============================================================================

INSERT INTO <SCHEMA>.<TABLE> (id, <owner_col>, <data_col>) VALUES
    (1, <user_id_alice>, '<alice data>'),
    (2, <user_id_bob>,   '<bob data>');

-- =============================================================================
-- SECTION 3: Owner can see/modify own row
-- =============================================================================

-- Switch identity. SET LOCAL keeps changes within the transaction so RESET ROLE
-- isn't strictly necessary at the end (ROLLBACK reverts the GUC).
SET LOCAL ROLE <restricted_role>;
SET LOCAL <user_id_setting> = '<user_id_alice>';

SELECT isnt_empty(
    $$SELECT * FROM <SCHEMA>.<TABLE> WHERE id = 1$$,
    'owner can see own row'
);

-- Owner can update own row
SELECT lives_ok(
    $$UPDATE <SCHEMA>.<TABLE> SET <data_col> = '<new>' WHERE id = 1$$,
    'owner can update own row'
);

-- =============================================================================
-- SECTION 4: Non-owner cannot see/modify
-- =============================================================================

-- Switch to a different user
SET LOCAL <user_id_setting> = '<user_id_bob>';

-- BLOCKED SELECT returns empty result, NOT an error
SELECT is_empty(
    $$SELECT * FROM <SCHEMA>.<TABLE> WHERE id = 1$$,
    'non-owner cannot see another user''s row (returns empty)'
);

-- BLOCKED INSERT throws 42501
SELECT throws_ok(
    $$INSERT INTO <SCHEMA>.<TABLE> (<owner_col>, <data_col>)
      VALUES (<user_id_alice>, 'impersonation')$$,
    '42501', NULL,
    'non-owner cannot impersonate another user on INSERT'
);

-- BLOCKED UPDATE: the WHERE clause filters out non-visible rows.
-- The UPDATE itself succeeds but affects 0 rows.
UPDATE <SCHEMA>.<TABLE> SET <data_col> = '<malicious>' WHERE id = 1;
SELECT is(
    (SELECT <data_col> FROM <SCHEMA>.<TABLE> WHERE id = 1),
    '<original_or_new>'::text,
    'non-owner UPDATE should affect 0 rows (WHERE filters out invisible rows)'
);

-- =============================================================================
-- SECTION 6: Cleanup
-- =============================================================================

-- SET LOCAL is reverted by ROLLBACK; explicit RESET ROLE is optional
RESET ROLE;
SELECT * FROM finish();
ROLLBACK;
