-- =============================================================================
-- pgTAP Test: constraints on <SCHEMA>.<TABLE>
-- Type: CONSTRAINTS
-- Generated by: pgtap-tdd-testing skill
-- Requirement: <BRIEF_DESCRIPTION>
--
-- Test BOTH acceptance (valid data succeeds) AND rejection (invalid data fails).
-- =============================================================================
BEGIN;
SELECT plan(<N>);

-- =============================================================================
-- SECTION 1: Structure
-- =============================================================================

-- Existence of each constraint type
SELECT has_pk('<SCHEMA>', '<TABLE>',
    '<table> should have a primary key');
SELECT has_check('<SCHEMA>', '<TABLE>',
    '<table> should have at least one CHECK constraint');

-- NOT NULL constraints
SELECT col_not_null('<SCHEMA>', '<TABLE>', '<required_col1>',
    '<required_col1> should be NOT NULL');
SELECT col_not_null('<SCHEMA>', '<TABLE>', '<required_col2>',
    '<required_col2> should be NOT NULL');

-- UNIQUE constraints
-- SELECT col_is_unique('<SCHEMA>', '<TABLE>', '<unique_col>',
--     '<unique_col> should be UNIQUE');

-- =============================================================================
-- SECTION 2: Acceptance — valid data succeeds
-- =============================================================================

PREPARE valid_insert AS
    INSERT INTO <SCHEMA>.<TABLE> (<col1>, <col2>, <col3>)
    VALUES (<valid_val1>, <valid_val2>, <valid_val3>);

SELECT lives_ok(
    'valid_insert',
    'valid data should be accepted'
);

-- =============================================================================
-- SECTION 3: Rejection — NOT NULL violation
-- =============================================================================

PREPARE null_insert AS
    INSERT INTO <SCHEMA>.<TABLE> (<col1>, <col2>)
    VALUES (NULL, <valid_val2>);

SELECT throws_ok(
    'null_insert',
    '23502',                              -- not_null_violation
    NULL,
    'NULL in <col1> should violate NOT NULL'
);

-- =============================================================================
-- SECTION 4: Rejection — CHECK violation
-- =============================================================================

PREPARE check_violation AS
    INSERT INTO <SCHEMA>.<TABLE> (<col1>, <constrained_col>)
    VALUES (<valid_val1>, <invalid_val>);

SELECT throws_ok(
    'check_violation',
    '23514',                              -- check_violation
    NULL,
    'invalid <constrained_col> should violate CHECK constraint'
);

-- =============================================================================
-- SECTION 5: Rejection — UNIQUE violation
-- =============================================================================

-- First insert succeeds
INSERT INTO <SCHEMA>.<TABLE> (<unique_col>, <col2>)
    VALUES (<unique_val>, <valid_val2>);

-- Duplicate fails
PREPARE dup_insert AS
    INSERT INTO <SCHEMA>.<TABLE> (<unique_col>, <col2>)
    VALUES (<unique_val>, <other_val>);

SELECT throws_ok(
    'dup_insert',
    '23505',                              -- unique_violation
    NULL,
    'duplicate <unique_col> should violate UNIQUE constraint'
);

-- =============================================================================
-- SECTION 6: Cleanup
-- =============================================================================

DEALLOCATE valid_insert;
DEALLOCATE null_insert;
DEALLOCATE check_violation;
DEALLOCATE dup_insert;

SELECT * FROM finish();
ROLLBACK;
