-- =============================================================================
-- pgTAP Test: <SCHEMA>.<VIEW_NAME>
-- Type: VIEW
-- Generated by: pgtap-tdd-testing skill
-- Requirement: <BRIEF_DESCRIPTION>
-- =============================================================================
BEGIN;
SELECT plan(<N>);

-- =============================================================================
-- SECTION 1: Structure / Existence
-- =============================================================================

SELECT has_view(
    '<SCHEMA>', '<VIEW>',
    '<view> should exist'
);

-- Exact column set (catches changes to the view definition)
SELECT columns_are(
    '<SCHEMA>', '<VIEW>',
    ARRAY['<col1>', '<col2>', '<col3>'],
    '<view> should expose exactly these columns'
);

-- =============================================================================
-- SECTION 2: Setup test data
-- =============================================================================

INSERT INTO <SOURCE_TABLE> (<col1>, <col2>, <col3>) VALUES
    (<val1_pass>, <val2>, <val3>),  -- should appear in view
    (<val1_skip>, <val2>, <val3>);  -- should be filtered out by view

-- =============================================================================
-- SECTION 3: Happy path — view applies its filter correctly
-- =============================================================================

-- Use set_eq for unordered comparison; results_eq requires ORDER BY in the view
SELECT set_eq(
    'SELECT <col1> FROM <SCHEMA>.<VIEW>',
    ARRAY[<val1_pass>],
    '<view> should return only matching rows'
);

-- Inversely, verify excluded rows are NOT returned
SELECT set_hasnt(
    'SELECT <col1> FROM <SCHEMA>.<VIEW>',
    ARRAY[<val1_skip>],
    '<view> should not return non-matching rows'
);

-- =============================================================================
-- SECTION 4: Edge case — empty view when no matching rows
-- =============================================================================

UPDATE <SOURCE_TABLE> SET <filter_col> = <non_matching_val>;

SELECT is_empty(
    'SELECT * FROM <SCHEMA>.<VIEW>',
    '<view> should be empty when no source rows match the filter'
);

-- =============================================================================
-- SECTION 6: Cleanup
-- =============================================================================

SELECT * FROM finish();
ROLLBACK;
