-- =============================================================================
-- pgTAP Test: <SCHEMA>.<PROCEDURE_NAME>(<ARG_TYPES>)
-- Type: PROCEDURE
-- Generated by: pgtap-tdd-testing skill
-- Requirement: <BRIEF_DESCRIPTION>
--
-- WARNING: If this procedure calls COMMIT or ROLLBACK internally, this
-- standard test pattern will NOT work — the internal COMMIT ends the test's
-- outer transaction. See references/advanced-patterns.md § 1 for workarounds.
-- =============================================================================
BEGIN;
SELECT plan(<N>);

-- =============================================================================
-- SECTION 1: Structure / Existence
-- =============================================================================

SELECT has_function(
    '<SCHEMA>', '<PROCEDURE>', ARRAY['<arg1_type>', '<arg2_type>'],
    '<procedure>(<args>) should exist'
);

SELECT is_procedure(
    '<SCHEMA>', '<PROCEDURE>', ARRAY['<arg1_type>', '<arg2_type>'],
    '<procedure> should be a procedure, not a function'
);

-- =============================================================================
-- SECTION 2: Setup test data
-- =============================================================================

-- INSERTs/UPDATEs needed to exercise the procedure
-- INSERT INTO <input_table> (...) VALUES (...);

-- =============================================================================
-- SECTION 3: Happy path behavior — procedure runs without error
-- =============================================================================

SELECT lives_ok(
    $$CALL <SCHEMA>.<PROCEDURE>(<args>)$$,
    '<procedure> should execute without error for valid inputs'
);

-- Verify side effects — the procedure has no return value, so test data state
SELECT is(
    (SELECT count(*)::integer FROM <output_table>
     WHERE <condition>),
    <expected_count>,
    'should produce <expected_count> rows in <output_table>'
);

SELECT is(
    (SELECT <column> FROM <output_table> WHERE <condition>),
    <expected_value>::<type>,
    '<column> should be <expected_value>'
);

-- =============================================================================
-- SECTION 4: Edge cases
-- =============================================================================

-- Empty input
SELECT lives_ok(
    $$CALL <SCHEMA>.<PROCEDURE>(<empty_input_args>)$$,
    'should handle empty input without error'
);

-- =============================================================================
-- SECTION 5: Error cases
-- =============================================================================

-- NULL parameter
SELECT throws_ok(
    $$CALL <SCHEMA>.<PROCEDURE>(NULL, <other_args>)$$,
    'P0001', NULL,
    'NULL parameter should raise error'
);

-- =============================================================================
-- SECTION 6: Cleanup
-- =============================================================================

SELECT * FROM finish();
ROLLBACK;
