#!/usr/bin/env bash
# =============================================================================
#  provision-branch-db.sh — Per-branch DB provisioning for Project Perseus
# =============================================================================
#  Purpose: Create a per-branch PostgreSQL 18 database (cloned from
#           dev_template via STRATEGY=FILE_COPY + file_copy_method=clone)
#           and generate the worktree's .env file.
#
#  Usage:
#    Called by postCreate.sh:
#      provision-branch-db.sh --worktree <path> --branch <branch>
#
#    Manual re-provisioning:
#      provision-branch-db.sh --worktree ~/dev/repos/.../feat-x --branch feat/x
#
#  Idempotent: drops existing DB before recreating (use with care!).
#  Compatibility: bash 3.2+
#
#  Exit codes:
#    0 — success
#    1 — generic error
#    2 — invalid branch name
#    3 — psql not found
#    4 — template missing or not datistemplate=true
#    5 — DB creation failed
# =============================================================================

set -euo pipefail

# --- Logging ---
_log()  { printf "[provision] %s\n" "$*"; }
_info() { printf "[provision] ℹ️  %s\n" "$*"; }
_ok()   { printf "[provision] ✅ %s\n" "$*"; }
_warn() { printf "[provision] ⚠️  %s\n" "$*" >&2; }
_err()  { printf "[provision] ❌ %s\n" "$*" >&2; }
_die()  { _err "$1"; exit "${2:-1}"; }

# --- Argument parsing ---
WORKTREE_PATH=""
BRANCH_NAME=""
while [ $# -gt 0 ]; do
    case "$1" in
        --worktree) WORKTREE_PATH="$2"; shift 2 ;;
        --branch)   BRANCH_NAME="$2";   shift 2 ;;
        *) _die "Unknown argument: $1" 1 ;;
    esac
done

[ -z "$WORKTREE_PATH" ] && _die "--worktree required" 1
[ -z "$BRANCH_NAME"   ] && _die "--branch required" 1

# --- Pre-flight ---
command -v psql >/dev/null 2>&1 || _die "psql not found in PATH" 3

# --- Resolve config ---
_git_cfg() {
    local v
    v="$(git -C "$WORKTREE_PATH" config --get "$1" 2>/dev/null || true)"
    [ -n "$v" ] && printf "%s" "$v" || printf "%s" "$2"
}

PG_HOST="$(_git_cfg perseus.pg.host    "${PERSEUS_PG_HOST:-localhost}")"
PG_PORT="$(_git_cfg perseus.pg.port    "${PERSEUS_PG_PORT:-5432}")"
PG_USER="$(_git_cfg perseus.pg.user    "${PERSEUS_PG_USER:-perseus}")"
PG_TEMPLATE="$(_git_cfg perseus.pg.template "${PERSEUS_PG_TEMPLATE:-dev_template}")"
DB_PREFIX="$(_git_cfg perseus.pg.dbprefix   "${PERSEUS_DB_PREFIX:-perseus}")"

PG_ADMIN_URL="postgres://${PG_USER}@${PG_HOST}:${PG_PORT}/postgres"

# --- Sanitize ---
_sanitize_db_name() {
    local raw="$1"
    local clean
    clean=$(printf '%s' "$raw" \
        | tr '[:upper:]' '[:lower:]' \
        | tr '/.\- ' '____' \
        | tr -cd 'a-z0-9_')
    [ -z "$clean" ] && return 1
    local prefix_len=$(( ${#DB_PREFIX} + 1 ))
    local max_clean=$(( 63 - prefix_len ))
    clean="${clean:0:$max_clean}"
    printf "%s_%s" "$DB_PREFIX" "$clean"
}

DB_NAME="$(_sanitize_db_name "$BRANCH_NAME")" || _die "Branch name produced empty DB name" 2
_info "Branch:    $BRANCH_NAME"
_info "Worktree:  $WORKTREE_PATH"
_info "DB name:   $DB_NAME"

# --- Validate template ---
TEMPLATE_OK=$(psql -X -At -v ON_ERROR_STOP=1 "$PG_ADMIN_URL" \
    -c "SELECT count(*) FROM pg_database WHERE datname='$PG_TEMPLATE' AND datistemplate;" \
    2>/dev/null || echo "0")
[ "$TEMPLATE_OK" = "1" ] || _die "Template '$PG_TEMPLATE' missing or not datistemplate=true" 4

# --- Hash-based ports ---
_hash_port() {
    local svc=$1 wt_path=$2 base
    case "$svc" in
        api) base=4000 ;;
        web) base=5000 ;;
        worker) base=6000 ;;
        *)   base=7000 ;;
    esac
    local h
    h=$(printf '%s' "$wt_path" | shasum 2>/dev/null | cut -c1-4 || echo "0000")
    echo $(( base + 16#$h % 900 ))
}

API_PORT=$(_hash_port api "$WORKTREE_PATH")
WEB_PORT=$(_hash_port web "$WORKTREE_PATH")

# --- Provision ---
_info "Provisioning DB (STRATEGY=FILE_COPY, file_copy_method=clone)…"
START_TS=$(date +%s)

if ! psql -X -v ON_ERROR_STOP=1 "$PG_ADMIN_URL" >/dev/null 2>&1 <<-SQL
    SELECT pg_terminate_backend(pid)
      FROM pg_stat_activity
     WHERE datname IN ('${DB_NAME}', '${PG_TEMPLATE}')
       AND pid <> pg_backend_pid();
    DROP DATABASE IF EXISTS "${DB_NAME}";
    CREATE DATABASE "${DB_NAME}"
        WITH TEMPLATE = "${PG_TEMPLATE}"
             STRATEGY = FILE_COPY
             OWNER    = "${PG_USER}";
SQL
then
    _die "DB provisioning failed for '$DB_NAME'" 5
fi

ELAPSED=$(( $(date +%s) - START_TS ))
_ok "Database '${DB_NAME}' created in ${ELAPSED}s"

# --- Generate .env ---
ENV_FILE="${WORKTREE_PATH}/.env"
DATABASE_URL="postgres://${PG_USER}@${PG_HOST}:${PG_PORT}/${DB_NAME}"

cat > "$ENV_FILE" <<-EOF
# =============================================================================
#  Auto-generated by provision-branch-db.sh — DO NOT COMMIT
# =============================================================================
#  Generated: $(date '+%Y-%m-%d %H:%M:%S %Z')
#  Branch:    ${BRANCH_NAME}
#  Worktree:  ${WORKTREE_PATH}
# =============================================================================

PERSEUS_BRANCH=${BRANCH_NAME}
PERSEUS_DB_NAME=${DB_NAME}
PERSEUS_PG_HOST=${PG_HOST}
PERSEUS_PG_PORT=${PG_PORT}
PERSEUS_PG_USER=${PG_USER}
PERSEUS_PG_TEMPLATE=${PG_TEMPLATE}

PGHOST=${PG_HOST}
PGPORT=${PG_PORT}
PGUSER=${PG_USER}
PGDATABASE=${DB_NAME}

DATABASE_URL=${DATABASE_URL}

PERSEUS_API_PORT=${API_PORT}
PERSEUS_WEB_PORT=${WEB_PORT}
EOF

_ok ".env written: ${ENV_FILE}"

# --- Summary ---
cat <<-EOF

  ┌─────────────────────────────────────────────────────────────────┐
  │  ✅  Worktree provisioning complete                              │
  ├─────────────────────────────────────────────────────────────────┤
  │  Branch     : ${BRANCH_NAME}
  │  Database   : ${DB_NAME}
  │  Connection : ${DATABASE_URL}
  │  API port   : ${API_PORT}
  │  Web port   : ${WEB_PORT}
  │
  │  Quick start:
  │    cd "${WORKTREE_PATH}"
  │    source .env
  │    psql
  │
  │  Open TMUX cockpit:
  │    gtr-tmux \$(basename "${WORKTREE_PATH}")
  │
  │  Run pgTAP tests:
  │    ./scripts/run-pgtap.sh
  └─────────────────────────────────────────────────────────────────┘

EOF
exit 0